### ISSUE TITLE
Would you please post a new release?

### ISSUE THREAD

**Issue by takatost** [sqrthree/vuepress-theme-api#2]
https://github.com/sqrthree/vuepress-theme-api/commit/6bb64386ec94719a1c49f2861ec5c97af2740796

this commit is not release, I'm having this BUG happening.

thx.

**Comment by sqrthree** [comment]
Thank you, a new version [v0.2.1](https://www.npmjs.com/package/vuepress-theme-api/v/0.2.1) is available here.
