### ISSUE TITLE
Send Request Sidepanel

### ISSUE THREAD

**Issue by zwcampbell** [sqrthree/vuepress-theme-api#9]
Hi! Great theme. The README makes it look like you can utilize a sidepanel to send requests. I didn't see any configuration for that in your docs. Is this an actual feature? If so, how is it enabled?

![image](https://user-images.githubusercontent.com/44709448/59521077-6fe61180-8e99-11e9-9eec-af6881b666ad.png)

**Comment by sqrthree** [comment]
I'm sorry that the English documents have not been published. It will be automatically generated when you use `<CURL>` components. The example can be found at [docs/zh/configurations/components.md#curl-%E7%BB%84%E4%BB%B6](https://github.com/sqrthree/vuepress-theme-api/blob/master/docs/zh/configurations/components.md#curl-%E7%BB%84%E4%BB%B6)

	<CURL>
	```bash
	curl -X POST http://api.example.com/api/auth/login \
	  --data '{
	    "username": "my-username",
	    "password": "my-password"
	  }'
	```
	</CURL>
